# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

include: package:lints/recommended.yaml

# Inspired by dart_flutter_team_lints

analyzer:
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    - always_declare_return_types
    - avoid_catching_errors
    - avoid_dynamic_calls
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - directives_ordering
    - omit_local_variable_types
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - public_member_api_docs
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_library_directive
    - unnecessary_parenthesis
    - unnecessary_statements
    - unreachable_from_main
    - use_is_even_rather_than_modulo