# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - conditional_uri_does_not_exist
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_relative_imports
    - unnecessary_parenthesis
    - prefer_single_quotes

analyzer:
  exclude:
    - lib/src/bindings/*
