# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
edition = "2024"
name = "cargo-c"
publish = false

[dependencies]
icu_capi = { path = "../../ffi/capi" }

[build-dependencies]
cc = "1.0"
